config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  devise_for :users

  resources :posts do
    resources :messages, only: [:index, :new, :create, :show, :destroy, :edit]
  end
  
   resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :post
  belongs_to :user


  validates :text, presence: true
  validates :post_id, presence: true
  # validates :user_id, presence: true

  # def was_attached?
  #   self.image.attached?
  # end
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags,through: :post_tag_relations
  
  has_many  :message
  

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  # validates :post_id, presence: true
  # validates :tag_id, presence: true
end

app/models/posts_tag.rb
class PostsTag

  include ActiveModel::Model
  attr_accessor :title, :sentence, :tag_name, :user_id

  with_options presence: true do
    validates :title
    validates :sentence
    validates :tag_name
    validates :user_id
  end

  def save(tag_list)
    post = Post.create(title: title, sentence: sentence, user_id: user_id)

      tag_list.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save

      PostTagRelation.create(post_id: post.id, tag_id: tag.id)
      end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations
  has_many :posts, through: :post_tag_relations

  validates :tag_name, uniqueness: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  
   mount_uploader :image, ImageUploader

  has_many :posts
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :image])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_post, only: [:index, :new, :create, :edit, :show]

  def index
    @messages = Message.all
    @message = Message.new
    @messages = @post.message.includes(:user)

    unless user_signed_in?
      redirect_to root_path
    end
  end
  
  def new
    @messages = Message.all
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @user = current_user 
    if @message.save
      ActionCable.server.broadcast "message_channel", content: @message, user: @user
    else
      render :index
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show,:create, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @posts = Post.order(id: :DESC)
    @tags = Tag.order(id: :DESC)
    @posts = Post.all.page(params[:page]).per(12)
  end

  def new
    @posts_tag = PostsTag.new
  end

  def create
    @posts_tag = PostsTag.new(post_params)
    tag_list = params[:posts_tag][:tag_name].split(",")
    if @posts_tag.valid?
      @posts_tag.save(tag_list)
      redirect_to root_path
    else
      render 'index'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end
  
  private

  def post_params
    params.require(:posts_tag).permit(:title, :tag_name, :sentence).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:new, :index, :new, :edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @posts = Post.all
    @tags = Tag.all
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to root_path
    end
  end
  
  def edit
  end

  private

  def set_user
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CommuT35544</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdn.webrtc.ecl.ntt.com/skyway-4.4.1.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<header class="hedw">
  <%= render "shared/second-header" %>
</header>

<div class="post-title-room">
<%= "タイトル：#{@post.title}" %>
</div>

<div class="chat-room-zen">
  <div class="chat-delete">
    <%= link_to "チャットを退出する", "/"%>
  </div>

  <div id="room">
  <%# <span id="video-end">ビデオ通話を止める</span> %>
  <room />
  </div>
  
  <%= javascript_pack_tag 'room' %>
  <%= stylesheet_pack_tag 'room' %>

  <div class="chat-main">
    <h3>チャット</h3>
    <span id="setumei">
      ※音声通話・ビデオを開始できるのは２名までです。<br>
      ※マイクのみ設定して話すことも可能です。<br>
      ※ビデオチャットを開始する場合は、「Your Peer ID」に書かれているIDを<br>
      　ビデオチャット相手に教えてあげてください。<br>
      　ID通知された方は「Call id」へ入力し[call]ボタンを押すとビデオチャットが開始します。<br>
    </span>
    <%= form_with model: [@user, @post, @message], local: false do |f| %>
      <%= f.text_field :text %>
      <%= f.submit '送信' %>
    <% end %>

    <div id='messages'>
      <% @messages.reverse_each do |message| %>
        <% if @post.user.name == message.user.name %>
          <div class="user-chat-right">
            <p><%= message.user.name %>
            <%= message.created_at %></p>
            <p><%= message.text %></p>
          </div>
        <% else %>
          <div class="user-chat-left">
            <p><%= message.user.name %>
            <%= message.created_at %></p>
            <p><%= message.text %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<footer>
  <%= render "shared/second-footer"%>
</footer>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<div class="main-title">
  <h2 class='service-title'>
    CommuTとは<br>「Communication」+「Treasure」
    <br>コミュニケーションは宝物である
  </h2>
</div>

<div class='main1'>
  <div class='title-contents'>
    <div class="a">
      <%= image_tag "LOVE01.png", class:"ai" %>
      <%= image_tag "test01.jpg", class:"ai" %>
      <%= image_tag "NYBIRU.jpg", class:"ai" %>
    </div>
</div>
<div class='post-contents'>
  <h2 class='post-list-name'>投稿一覧</h2>
  <div class="pageing">
    <%= paginate @posts %>
  </div>
  <ul class='post-lists'>

    <% @posts.each do |post| %>
    
      <li class='list'>
          <div class='post-title'>
            <%= link_to post_path(post.id), method: :get do %>
              <%= post.title %>
            <% end %>
          </div>
          <h2 id="tag-name-tag">タグ：</h2>
          <div class="post-tag">
            <% post.tags.each do |tag| %>
              <%=tag.tag_name%>
            <% end %>
          </div>
      </li>
    <% end %>
  </ul>
</div>



<%= link_to new_post_path, method: :get, class: 'purchase-btn'  do %>
  <span class='purchase-btn-text'></span> 
  <%= image_tag 'touko.png' , size: '1000px' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<header class="hed">
  <%= render "shared/header" %>
</header>

<div class="posts-sell-contents">
  <div class="posts-sell-main">
    <h2 class="posts-sell-title">投稿フォーム</h2>
    <%= form_with model:@posts_tag, url: posts_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="post-form">
      <div class="new-posts">
          タイトル入力
          <span class="indispensable">必須</span>
        <%= f.text_area :title, class:"title-text", id:"title", placeholder:"タイトル名（必須 40文字まで)", maxlength:"40" %>
        <div class="posts-explain">
          <div class="new-tag">
            タグ入力
            <%= f.text_field :tag_name, class:"input-tag", id:"name", placeholder:"複数タグを入力する際は、[,]で区切ることで入力されます。" %>
          </div>
          <div id="search-result"></div>
          <div class="weight-bold-text">
            メッセージ
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :sentence, class:"message-text", id:"message", placeholder:"メッセージ（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
    </div>


    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

<footer>
  <%= render "shared/second-footer"%>
</footer>

app/views/posts/show.html.erb
<header class="hed">
  <%= render "shared/header" %>
</header>

<%# 投稿概要 %>

<div class="posts-sell-contents">
  <%= "#{@post.user.name}さんの投稿表示" %>
  <div class="posts-waku">
    <div class="post-title-show">
      <%= "#{@post.title}" %>
    </div>
    <div class="post-box">
      <div class="post-tag-show">
        <div class="tag-title">タグ</div>
        <% @post.tags.each do |tag| %>
          <div class="tag-name">
          <%=tag.tag_name%>
          </div>
        <%end%>
      </div>
      <br>
      <div class="post-message">
        <span id="post-show">
        メッセージ内容<br>
        </span>
          <div class="post-show-message">
          <%=safe_join(@post.sentence.split("\n"),tag(:br))%>
        </div>
      </div>

      <br>

      <div class="rooms-page">
        <% if user_signed_in? %>
          <%= link_to post_messages_path(@post), method: :get, class: 'room-btn'  do %>
            <%= image_tag 'Chatbtn.png' , size: '250x80' ,class: "room-go-btn" %>
          <% end %>
        <% else %>
          <%= link_to "/", method: :get, class: 'room-btn'  do %>
            <%= image_tag 'Chatbtn.png' , size: '250x80' ,class: "room-go-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <span id='ad-footer-explain'>
    ページ上部へ
  </span>

</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>CommuTについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'CommuT利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <%# <div class='furima-details'>
      <h2 class='footer-content-head'>CommuTを見る</h2>
      <ul> %>
        <%#=<li> link_to 'タグ一覧', "#", class: "footer-link" </li>%>
        <%#=<li> link_to '人気一覧', "#", class: "footer-link" </li>%>
      <%# </ul>
    </div> %>
    <div class='furima-details'>
      <h2 class='footer-content-head'>CommuTについて</h2>
      <ul>
        <li><%= link_to 'CommuTガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'CommuTロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("logo(commut).jpg", class:"logo-white"), "#" %>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='logo-contents'>
    <%= link_to image_tag("logo(commut).png", class:"icon"), "/" %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <form class="search-form" action="#">
        <input class='input-box' placeholder='タグ検索'>
        <button class="search-button">
          <%= image_tag "search.png", class:"search-icon" %>
        </button>
      </form>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><img src=<%= current_user.image %> class = "icon_image"></li>
        <li><%= link_to current_user.name, user_path(current_user.id), class: "name_a" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-footer'>
  <div class='second-footer-text-wrap'>
    <p class='second-footer-text'>プライバシーポリシー</p>
    <p class='second-footer-text'>Commut利用規約</p>
  </div>
  <%= image_tag "logo(commut).png", class:"second-footer-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo(commut).png", class:"second-logo"), "/" %>
</header>

app/views/top/index.html.erb
<%= render "shared/header" %>

<div class="main-title">
  <h2 class='service-title'>
    CommuTとは<br>「Communication」+「Treasure」
    <br>コミュニケーションは宝物である
  </h2>
</div>

<p class='service-subtitle1'>
 すぐ見つかる。
</p>

<p class='service-subtitle2'>
 すぐ繋がる。
</p>

<p class='service-subtitle3'>
 それは<br>『コミュット』
</p>

<div class='main1'>
  <div class='title-contents'>
    <div class="a">
      <%= image_tag "LOVE01.png", class:"ai" %>
      <%= image_tag "test01.jpg", class:"ai" %>
      <%= image_tag "NYBIRU.jpg", class:"ai" %>
    </div>
</div>

<%= link_to "#", method: :get, class: 'purchase-btn'  do %>
  <span class='purchase-btn-text'></span> 
  <%= image_tag 'touko.png' , size: '1000px' ,class: "purchase-btn-icon" %>
  <%#= image_tag 'ittoku.png' , size: '100px' ,class: "purchase-btn-icon2" %>
<% end %>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%#= render "shared/header" %>

<%# 投稿概要 %>

<div class="post-show">
<%= "#{@user.name}さんの投稿一覧" %>
  <div class="item-box">

  </div>
</div>

<%#= render "shared/footer" %>